# Generated by Django 4.0.6 on 2022-07-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_posting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=50)),
                ('notes', models.TextField(max_length=150)),
            ],
        ),
        migrations.AlterModelOptions(
            name='posting',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='posting',
            name='date',
            field=models.DateField(verbose_name='posting date'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contacts',
            field=models.ManyToManyField(to='main_app.contact'),
        ),
    ]
